services:
  base:
    build:
      context: .
      dockerfile: docker/base.dockerfile
    image: ttfemesh-base
    container_name: ttfemesh-base
    command: bash

  lib:
    build:
      context: .
      dockerfile: docker/lib.dockerfile
    depends_on:
      - base
    image: ttfemesh-lib
    container_name: ttfemesh-lib
    command: python

  dev:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    image: ttfemesh-dev
    container_name: ttfemesh-dev
    volumes:
      - .:/app
    depends_on:
      - base
    command: bash

  docs:
    build:
      context: .
      dockerfile: docker/docs.dockerfile
    image: ttfemesh-docs
    container_name: ttfemesh-docs
    volumes:
      - .:/app
    depends_on:
      - dev
    ports:
      - "8000:8000"
    command: bash /app/docs/serve_docs.sh

  notebook:
    build:
      context: .
      dockerfile: docker/notebook.dockerfile
    image: tnfemesh-notebook
    container_name: ttfemesh-notebook
    volumes:
      - .:/app
    depends_on:
      - dev
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
