services:
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: tnfemesh
    container_name: tnfemesh
    command: python

  dev:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    image: tnfemesh-dev
    container_name: tnfemesh-dev
    volumes:
      - .:/app
    depends_on:
      - base
    command: bash

  notebooks:
    build:
      context: .
      dockerfile: docker/notebook.dockerfile
    image: tnfemesh-notebook
    container_name: tnfemesh-notebook
    volumes:
      - ./notebooks:/app/notebooks
    depends_on:
      - base
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
