services:
  base:
    build:
      context: .
      dockerfile: docker/base.dockerfile
    image: tnfemesh-base
    container_name: tnfemesh-base
    command: bash

  lib:
    build:
      context: .
      dockerfile: docker/lib.dockerfile
    depends_on:
      - base
    image: tnfemesh-lib
    container_name: tnfemesh-lib
    command: python

  dev:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    image: tnfemesh-dev
    container_name: tnfemesh-dev
    volumes:
      - .:/app
    depends_on:
      - base
    command: bash

  notebook:
    build:
      context: .
      dockerfile: docker/notebook.dockerfile
    image: tnfemesh-notebook
    container_name: tnfemesh-notebook
    volumes:
      - .:/app
    depends_on:
      - dev
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
